db.url=jdbc:mysql://localhost:3306/placementpro_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
db.user=root
db.password=@AMMUSHUBU72

# Add your Gemini API key later for Phase 6
gemini.api.key=AIzaSyBF8_0_8-2P4Tkmz69GuZq-7pLWx_yKPGE
